version: '3.9'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
    ports:
      - '3000:3000'
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/app'
    ports:
      - '5000:5000'